In [17]:
# So we can load files from other sub-directories, e.g. datasets.
import os
import sys
module_path = os.path.abspath(os.path.join('unlabeled_extrapolation'))
if module_path not in sys.path:
    sys.path.append(module_path)
    
from unlabeled_extrapolation.models import imnet_resnet
from unlabeled_extrapolation.models import imnet_models
from unlabeled_extrapolation.models import clip_model
from unlabeled_extrapolation.models import vit_model
from torch import nn
import torch
import torchvision
import numpy as np
import glob
import pickle
import unlabeled_extrapolation.utils.utils as utils

from unlabeled_extrapolation.datasets import fmow

import importlib
importlib.reload(imnet_resnet)
importlib.reload(imnet_models)
importlib.reload(fmow)


<module 'unlabeled_extrapolation.datasets.fmow' from '/juice/scr/ananya/cifar_experiments/unlabeled_extrapolation/unlabeled_extrapolation/datasets/fmow.py'>

In [8]:
vitb16 = vit_model.VitModel('dino_vitb16')

Using cache found in /sailhome/ananya/.cache/torch/hub/facebookresearch_dino_main


In [18]:
vitb16.set_requires_grad(False)
vitb16.new_last_layer(30)
print(vitb16.get_last_layer())

NameError: name 'vitb16' is not defined

In [28]:
model = imnet_resnet.ResNet50(pretrained=True, pretrain_style='mocov2', checkpoint_path='/u/scr/ananya/simclr_weights/moco_v2_800ep_pretrain.pth.tar')

# Try loading fmow checkpoints

In [36]:
model1 = imnet_resnet.ResNet50(pretrained=True, pretrain_style='mocov2', checkpoint_path='/u/scr/ananya/simclr_weights/moco_checkpoint_0200.pth.tar')

In [10]:
model2 = imnet_resnet.ResNet50(pretrained=True, pretrain_style='mocov2', checkpoint_path='/u/scr/ananya/simclr_weights/mocotp_checkpoint_0200.pth.tar')

# Load fmow

In [8]:
trans = torchvision.transforms.Compose(
[
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
fmow_dataset = fmow.Fmow(split='test', regions=['all'], root='/u/scr/nlp/wilds/data', transform=trans)
# use 'train', 'ood_val', 'test'

In [30]:
print(type(fmow_dataset[0][0]))
model.enable_side_tuning()
model.cuda()
output = model(fmow_dataset[0][0].cuda().unsqueeze(0))
# output = vitb16(fmow_dataset[0][0].cuda().unsqueeze(0))
print(output.shape)

<class 'torch.Tensor'>
torch.Size([1, 2048]) torch.Size([1, 2048])
torch.Size([1, 1000])


In [37]:
def count_parameters(model, trainable):
    return sum(p.numel() for p in model.parameters() if p.requires_grad == trainable)
print(count_parameters(model, trainable=False))
print(count_parameters(model, trainable=True))
# for p in model.parameters():
#     print(p.is_cuda)

23508032
27606032
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [25]:
len(fmow_dataset)

22108

In [12]:
fmow_dataset[0][0].shape

torch.Size([3, 224, 224])

In [3]:
fmow_loader = torch.utils.data.DataLoader(fmow_dataset, batch_size=64, shuffle=True, num_workers=2)
# model2.cuda()
# model2.train()
labels_list = []

for data in fmow_loader:
    print('hi')
    images, labels = data
    labels_list.append(labels.cpu().numpy())
#     images = images.cuda()
#     outputs = model2(images)


hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi


In [10]:
# As you can see there are missing elements.
unique_elements = np.unique(np.concatenate(labels_list))
for i in range(62):
    if i not in unique_elements:
        print(i)
print(unique_elements)

30
57
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 58 59 60 61]


In [54]:
num_classes = 62
missing_elements = [30, 57]

def get_updated_weights(weights,  biases, num_classes, missing_elements):
    padded_elements = missing_elements + [num_classes]
    assert weights.shape[0] + len(missing_elements) == num_classes
    feat_size = weights.shape[1]
    new_weights = np.zeros((num_classes, feat_size))
    new_biases = np.zeros((num_classes,))
    prev = 0
    for i in range(len(padded_elements)):
        cur = padded_elements[i]
        new_weights[prev:cur] = weights[prev-i:cur-i]
        new_biases[prev:cur] = biases[prev-i:cur-i]
        if cur < num_classes:
            new_biases[cur] = -1000.0
        prev = cur+1
    return new_weights, new_biases

def update_weights(num_classes=62, missing_elements=[30, 57], results_dir='.'):
    file_paths = glob.glob(results_dir + 'weights*.pkl', recursive=True)
    for file_path in file_paths:
        print(file_path)
        weights, biases, a, b = pickle.load(open(file_path, 'rb'))
        print(weights.shape, biases.shape)
        new_weights, new_biases = get_updated_weights(weights,  biases, num_classes, missing_elements)
        print(new_weights.shape, new_biases.shape)
        print(new_weights[30], new_weights[56])
        archive_file_path = file_path[:-4] + '_old.pkl'
        pickle.dump( (weights, biases, a, b), open(archive_file_path, "wb" ) )
        pickle.dump( (new_weights, new_biases, a, b), open(archive_file_path, "wb" ) )
update_weights(results_dir='/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/linprobe_fmow_mocotp_fmow_resnet50/')

/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/linprobe_fmow_mocotp_fmow_resnet50/weights_0.pkl
(60, 2048) (60,)
(62, 2048) (62,)
[0. 0. 0. ... 0. 0. 0.] [-0.77600142  0.26469648  0.44337508 ...  0.76615316 -0.02349414
  1.0102488 ]
/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/linprobe_fmow_mocotp_fmow_resnet50/weights_0_old.pkl
(60, 2048) (60,)
(62, 2048) (62,)
[0. 0. 0. ... 0. 0. 0.] [-0.77600142  0.26469648  0.44337508 ...  0.76615316 -0.02349414
  1.0102488 ]
/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/linprobe_fmow_mocotp_fmow_resnet50/weights_1_old.pkl
(60, 2048) (60,)
(62, 2048) (62,)
[0. 0. 0. ... 0. 0. 0.] [-0.77448514  0.264641    0.44119132 ...  0.76753556 -0.02327004
  1.01224038]
/u/scr/ananya/cifar_experiments/unlabeled_extrapolation/logs/linprobe_fmow_mocotp_fmow_resnet50/weights_1.pkl
(60, 2048) (60,)
(62, 2048) (62,)
[0. 0. 0. ... 0. 0. 0.] [-0.77448514  0.264641    0.44119132 ...  0.76753556 -0.02327004
  1.01224038]
/u/s

In [15]:
# What happens with logistic regression if there are missing labels (e.g. labels are 0 or 4)?
# sklearn would treat it as binary classification, but output 0 or 4 (instead of 0, 1)
from sklearn.linear_model import LogisticRegression
X = [[-1], [-2], [1.0], [-3.0], [4.0], [0.0], [1.0], [0.2]]
y = [1, 1, 1, 1, 4, 4, 4, 4]
clf = LogisticRegression(random_state=0).fit(X, y)
clf.coef_

array([[0.79114543]])

# Examine model

In [7]:
# Print to make sure model1 and model2 are different, so loading is actually doing something.
print(list(list(model2._model.children())[0].parameters()))

[Parameter containing:
tensor([[[[ 4.5925e-02,  2.4501e-02,  1.7135e-02,  ...,  3.4709e-02,
           -3.0446e-02, -3.3597e-02],
          [ 2.7815e-02,  1.9076e-02,  1.7268e-02,  ...,  4.9695e-02,
           -2.4068e-02, -3.3174e-02],
          [ 8.5390e-03,  1.2160e-02,  2.2308e-02,  ...,  7.1529e-02,
           -1.3284e-03, -1.3955e-02],
          ...,
          [-7.1822e-03,  2.3723e-02,  5.7477e-02,  ...,  7.8695e-02,
           -2.4064e-03,  9.9170e-03],
          [-8.3695e-02, -6.1164e-02, -5.1117e-03,  ...,  2.0737e-02,
           -6.2004e-02, -6.9332e-02],
          [-8.0871e-02, -7.3265e-02, -1.3761e-02,  ...,  4.8501e-02,
           -4.5042e-02, -6.3812e-02]],

         [[-1.3739e-01, -9.2955e-02, -7.8492e-02,  ..., -6.5235e-03,
           -4.8398e-02, -5.8640e-02],
          [-8.9618e-02, -3.5499e-02, -1.5408e-02,  ...,  8.3488e-02,
            4.3193e-02,  2.9939e-02],
          [-7.1726e-02, -4.7808e-03,  1.8898e-02,  ...,  1.3059e-01,
            1.0011e-01,  8.2546e-02

# Try to examine layers, children, parameters

In [11]:
def count_parameters(model, trainable):
    return sum(p.numel() for p in model.parameters() if p.requires_grad == trainable)

In [12]:
list(model._model.children())[-3]

Sequential(
  (0): Bottleneck(
    (conv1): Conv2d(1024, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv3): Conv2d(512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn3): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (downsample): Sequential(
      (0): Conv2d(1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False)
      (1): BatchNorm2d(2048, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (1): Bottleneck(
    (conv1): Conv2d(2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): 

In [13]:
# Tuning batch norm parameters only.
model._model.eval()
model.set_requires_grad(False)
for layer in model._model.modules():
    if isinstance(layer,nn.modules.batchnorm.BatchNorm2d): 
        for param in layer.parameters():
            param.requires_grad = True

count_parameters(model, True)

53120

In [14]:
model._model.eval()
model.set_requires_grad(False)
num_layers_fine_tune = 5
for child in list(model._model.children())[:num_layers_fine_tune]:
    for param in child.parameters():
            param.requires_grad = True
count_parameters(model, True)

225344

In [15]:
def get_params(layers):
    params = []
    for layer in layers:
        for param in layer.parameters():
            params.append(param)
    return params

base_params = get_params(list(model._model.children())[:-1])
fc_params = get_params(list(model._model.children())[-1:])
len(base_params)

159

In [16]:
list(model._model.named_children())

[('conv1',
  Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)),
 ('bn1',
  BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)),
 ('relu', ReLU(inplace=True)),
 ('maxpool',
  MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)),
 ('layer1',
  Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), str

In [134]:
swav_path = '/u/scr/ananya/simclr_weights/swav_800ep_pretrain.pth.tar'
model = imnet_resnet.ResNet50(pretrained=True, pretrain_style='swav', checkpoint_path=swav_path)

In [135]:
model

ResNet50(
  (_model): Sequential(
    (resnet): ResNet(
      (padding): ConstantPad2d(padding=(1, 1, 1, 1), value=0.0)
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(2, 2), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affi

In [8]:
from unlabeled_extrapolation.datasets import breeds
entity30 = breeds.Breeds(root='/u/scr/nlp/imagenet/', breeds_name='entity30', transform=trans, split='val')

NameError: name 'trans' is not defined

In [11]:
import torchvision
import torch
import torchvision.transforms as transforms
trans = transforms.Compose(
[
    transforms.Resize(size=[224,224]),
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])
x = torch.unsqueeze(trans(entity30[0][0]), axis=0)
x = x.cuda()
print(x.shape)
model.eval()
model.cuda()
z = model._model(x)

torch.Size([1, 3, 224, 224])


In [18]:
print(len(entity30))

6000


In [19]:
for i in range(5):
    print(i)
    loader = torch.utils.data.DataLoader(entity30, batch_size=64,shuffle=True, num_workers=2)
    with torch.no_grad():
        for data in loader:
            print('hi')
            images, labels = data
            images = images.cuda()
            outputs = model(images)


0
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
1
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
2
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
3
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi
hi